# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: devxt_count_pb2.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'devxt_count_pb2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64\x65vxt_count_pb2.proto\x12\x0b\x64\x65vxt_count\"\x14\n\x05\x44\x45VXT\x12\x0b\n\x03tag\x18\x01 \x01(\t\"]\n\x03\x44\x65v\x12\x0b\n\x03UID\x18\x01 \x01(\x03\x12\x16\n\x0ePlayerNickname\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x05 \x01(\t\x12!\n\x05\x64\x65vxt\x18\x16 \x01(\x0b\x32\x12.devxt_count.DEVXT\"+\n\x02xt\x12%\n\x0b\x41\x63\x63ountInfo\x18\x01 \x01(\x0b\x32\x10.devxt_count.Devb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'devxt_count_pb2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVXT']._serialized_start=38
  _globals['_DEVXT']._serialized_end=58
  _globals['_DEV']._serialized_start=60
  _globals['_DEV']._serialized_end=153
  _globals['_XT']._serialized_start=155
  _globals['_XT']._serialized_end=198
# @@protoc_insertion_point(module_scope)
