# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetFriend_Res.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13GetFriend_Res.proto\"*\n\tGetFriend\x12\x1d\n\nPlayerList\x18\x01 \x03(\x0b\x32\t.MainList\"F\n\x08MainList\x12\x11\n\tPlayerUid\x18\x01 \x01(\x03\x12\x12\n\nPlayerName\x18\x03 \x01(\t\x12\x13\n\x0bPlayerLevel\x18\x08 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetFriend_Res_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETFRIEND']._serialized_start=23
  _globals['_GETFRIEND']._serialized_end=65
  _globals['_MAINLIST']._serialized_start=67
  _globals['_MAINLIST']._serialized_end=137
# @@protoc_insertion_point(module_scope)
