# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spam_join.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'spam_join.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fspam_join.proto\"\xa2\x04\n\tspam_join\x12\x0f\n\x07\x66ield_1\x18\x01 \x01(\x05\x12%\n\x07\x66ield_2\x18\x02 \x01(\x0b\x32\x14.spam_join.SubField2\x1a\xdc\x03\n\tSubField2\x12\x0f\n\x07\x66ield_1\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12/\n\x07\x66ield_3\x18\x03 \x01(\x0b\x32\x1e.spam_join.SubField2.SubField3\x12\x0f\n\x07\x66ield_4\x18\x04 \x01(\x05\x12\x0f\n\x07\x66ield_5\x18\x05 \x01(\x05\x12\x0f\n\x07\x66ield_6\x18\x06 \x01(\x05\x12\x10\n\x08\x66ield_10\x18\n \x01(\x05\x12\x10\n\x08\x66ield_11\x18\x0b \x01(\x03\x12\x10\n\x08\x66ield_12\x18\x0c \x01(\x05\x12\x31\n\x08\x66ield_15\x18\x0f \x01(\x0b\x32\x1f.spam_join.SubField2.SubField15\x12\x10\n\x08\x66ield_16\x18\x10 \x01(\x05\x12\x31\n\x08\x66ield_18\x18\x12 \x01(\x0b\x32\x1f.spam_join.SubField2.SubField18\x1a-\n\tSubField3\x12\x0f\n\x07\x66ield_2\x18\x01 \x01(\x05\x12\x0f\n\x07\x66ield_3\x18\x02 \x01(\x05\x1a.\n\nSubField15\x12\x0f\n\x07\x66ield_1\x18\x01 \x01(\x05\x12\x0f\n\x07\x66ield_2\x18\x02 \x01(\x05\x1a?\n\nSubField18\x12\x0f\n\x07\x66ield_1\x18\x01 \x01(\r\x12\x0f\n\x07\x66ield_2\x18\x02 \x01(\x05\x12\x0f\n\x07\x66ield_3\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spam_join_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPAM_JOIN']._serialized_start=20
  _globals['_SPAM_JOIN']._serialized_end=566
  _globals['_SPAM_JOIN_SUBFIELD2']._serialized_start=90
  _globals['_SPAM_JOIN_SUBFIELD2']._serialized_end=566
  _globals['_SPAM_JOIN_SUBFIELD2_SUBFIELD3']._serialized_start=408
  _globals['_SPAM_JOIN_SUBFIELD2_SUBFIELD3']._serialized_end=453
  _globals['_SPAM_JOIN_SUBFIELD2_SUBFIELD15']._serialized_start=455
  _globals['_SPAM_JOIN_SUBFIELD2_SUBFIELD15']._serialized_end=501
  _globals['_SPAM_JOIN_SUBFIELD2_SUBFIELD18']._serialized_start=503
  _globals['_SPAM_JOIN_SUBFIELD2_SUBFIELD18']._serialized_end=566
# @@protoc_insertion_point(module_scope)
